# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-02 16:38
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('group', models.CharField(max_length=64, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('sink', 'Sink'), ('source', 'Source'), ('costsurface', 'Cost Surface')], max_length=16)),
                ('data_product_uri', models.CharField(max_length=64)),
                ('original_data_product_uri', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaptoolConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', models.CharField(max_length=128, null=True, validators=[django.core.validators.RegexValidator(regex='^-?\\d+(\\.\\d+)?(,-?\\d+(\\.\\d+)?){3}$')])),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maptool', to='simccs_maptool.Case')),
            ],
        ),
        migrations.CreateModel(
            name='MaptoolData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.TextField(null=True)),
                ('bbox', models.CharField(max_length=128, null=True, validators=[django.core.validators.RegexValidator(regex='^-?\\d+(\\.\\d+)?(,-?\\d+(\\.\\d+)?){3}$')])),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simccs_maptool.Dataset')),
                ('maptool_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='simccs_maptool.MaptoolConfig')),
            ],
        ),
    ]
