# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-10 10:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simccs_maptool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maptooldata',
            name='popup',
            field=models.CharField(max_length=128, null=True, validators=[django.core.validators.RegexValidator(regex='^[^,]+(,[^,])+$')]),
        ),
    ]
