# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-11 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simccs_maptool', '0002_maptooldata_popup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
