# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-17 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simccs_maptool', '0003_auto_20201211_0847'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='case',
            unique_together=set([('owner', 'title')]),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('owner', 'name')]),
        ),
    ]
