# Generated by Django 2.2.17 on 2021-02-11 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simccs_maptool', '0004_auto_20201217_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='group',
        ),
        migrations.CreateModel(
            name='SimccsProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=64, null=True)),
                ('airavata_project', models.CharField(max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='simccs_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simccs_maptool.SimccsProject'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='simccs_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simccs_maptool.SimccsProject'),
        ),
    ]
