# Generated by Django 2.2.17 on 2021-02-11 09:35

from django.db import migrations


def create_default_simccs_project(apps, schema_editor):
    # Find all users with Datasets or Cases and create a default SimCCS Project for them
    Dataset = apps.get_model('simccs_maptool', 'Dataset')
    Case = apps.get_model('simccs_maptool', 'Case')
    SimccsProject = apps.get_model('simccs_maptool', 'SimccsProject')
    user_ids = Dataset.objects.values_list('owner', flat=True).union(
        Case.objects.values_list('owner', flat=True))
    for user_id in user_ids:
        simccs_project = SimccsProject.objects.create(name="Default", owner_id=user_id)
        Dataset.objects.filter(owner_id=user_id).update(simccs_project=simccs_project)
        Case.objects.filter(owner_id=user_id).update(simccs_project=simccs_project)


class Migration(migrations.Migration):

    dependencies = [
        ('simccs_maptool', '0005_auto_20210211_0934'),
    ]

    operations = [
        migrations.RunPython(create_default_simccs_project, migrations.RunPython.noop)
    ]
