# Generated by Django 2.2.17 on 2021-02-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simccs_maptool', '0006_auto_20210211_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='simccs_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simccs_maptool.SimccsProject'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='simccs_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simccs_maptool.SimccsProject'),
        ),
    ]
