# Generated by Django 2.2.17 on 2021-03-16 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simccs_maptool', '0007_auto_20210211_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_id', models.CharField(max_length=255, unique=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='simccs_maptool.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simccs_maptool.Case')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('case', 'owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='simccs_maptool.Workspace'),
        ),
        migrations.CreateModel(
            name='ScenarioSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simccs_maptool.Dataset')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='simccs_maptool.Scenario')),
            ],
            options={
                'unique_together': {('scenario', 'dataset', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioSink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sink_id', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simccs_maptool.Dataset')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinks', to='simccs_maptool.Scenario')),
            ],
            options={
                'unique_together': {('scenario', 'dataset', 'sink_id')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='simccs_maptool.Scenario')),
            ],
            options={
                'unique_together': {('scenario', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioExperimentParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='simccs_maptool.ScenarioExperiment')),
            ],
            options={
                'unique_together': {('experiment', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='scenario',
            unique_together={('workspace', 'title')},
        ),
    ]
