# Generated by Django 2.2.17 on 2021-03-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simccs_maptool', '0008_auto_20210316_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='scenario_id',
            field=models.CharField(default='scenario1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='scenario',
            unique_together={('workspace', 'title'), ('workspace', 'scenario_id')},
        ),
    ]
