# Generated by Django 2.2.17 on 2021-03-17 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simccs_maptool', '0009_auto_20210317_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
