# Generated by Django 2.2.17 on 2021-03-23 09:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simccs_maptool', '0011_userpreference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('simccs_project', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together={('simccs_project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='simccsproject',
            unique_together={('owner', 'name')},
        ),
    ]
