# Generated by Django 2.2.17 on 2021-03-29 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simccs_maptool', '0012_auto_20210323_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('data_product_uri', models.CharField(max_length=64)),
                ('original_data_product_uri', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='simccs_maptool.Dataset')),
            ],
            options={
                'unique_together': {('dataset', 'version')},
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='current_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='simccs_maptool.DatasetVersion'),
        ),
    ]
