# Generated by Django 2.2.17 on 2021-03-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simccs_maptool', '0014_auto_20210329_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='data_product_uri',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='original_data_product_uri',
        ),
        migrations.AlterField(
            model_name='datasetversion',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
