# Generated by Django 2.2.17 on 2021-05-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simccs_maptool', '0016_dataset_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='maptooldata',
            name='symbol',
            field=models.CharField(default='circle', max_length=32),
        ),
    ]
