# Generated by Django 2.2.17 on 2021-07-06 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simccs_maptool', '0017_maptooldata_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioExperimentDatasetVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='simccs_maptool.DatasetVersion')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='simccs_maptool.ScenarioExperiment')),
            ],
            options={
                'unique_together': {('experiment', 'dataset_version')},
            },
        ),
        migrations.AddField(
            model_name='scenarioexperiment',
            name='dataset_versions',
            field=models.ManyToManyField(through='simccs_maptool.ScenarioExperimentDatasetVersion', to='simccs_maptool.DatasetVersion'),
        ),
    ]
